apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-config
  namespace: cinema-exam
data:
  # relaxed binding : MOVIE_ENVIRONMENT -> movie.environment
  MOVIE_ENVIRONMENT: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-config
  namespace: cinema-exam
data:
  # relaxed binding : MOVIE_URL -> movie.url
  # "movie" = nom du Service Kubernetes, résolu par le DNS interne du namespace
  MOVIE_URL: http://movie:8080
